### ISSUE TITLE
Architect

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-3-practica-architect-JeroRoque#1]
[Práctica3_el_Jeronima_Roque.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-JeroRoque/files/12556057/Practica1_el_Architect.pdf)

**Comment by lucero012** [comment]
portada: 5
procedimientos: 4
imágenes: 3; le faltaron ilustraciones y descripción a cada una de ellas
resultados y conclusiones: 4
calificación:  16

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
